version: '3'
services:
  app:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - focasoft-back

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - focasoft-back

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: focasoft
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: focasoft
      MYSQL_PASSWORD: root
    networks:
      - focasoft-back

networks:
  focasoft-back:
    driver: bridge